coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: null
        base: auto
        paths:
          - !smellydash
          - !src/frc/team1983/constants
          - !src/frc/Robot.java
          - !src/frc/Main.java
          - !src/frc/utilities/sensors
    project:
      default:
        target: auto
        threshold: null
        base: auto
        paths:
          - !smellydash
          - !src/frc/team1983/constants
          - !src/frc/Robot.java
          - !src/frc/Main.java
          - !src/frc/utilities/sensors